### PR TITLE
Feature new updates

### PR DESCRIPTION
**Pull request by Bavon101**
- Updated README.md files
- Changed header-text color

### CODE REVIEW

**Comment by ShoiraTa** [comment]
STATUS: CHANGES REQUIRED 🟡 
----
Hi @Bavon101 

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

**First let me to point out:**

- Great commit history! ✔️ 
- Professional pull request! ✔️ 

Keep on coding, good job so far! :clap:

There are some issues that you still need to work on to go to the next project but you are almost there!



 ## Required Changes  :recycle: 

- [ ] Based on retirements, Linter result should be green. Linter should report NO errors. However in your case two tests are failing 
image
 >please fix the errors and submit project for a new review. 

_Check the comments under the review._ 

## Optional suggestions

- [ ]  [OPTIONAL] I have noticed that you already have half of your project in main branch, which is a wrong approach. I strongly suggest you to keep all the changes for the current milestone in a feature branch and DO NOT MERGE it before approval 😉 

 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

***
Cheers and Happy coding! :clap: :clap: :clap:

Code review by **Shoira**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Bavon101** [comment]
> ## STATUS: CHANGES REQUIRED 🟡
> Hi @Bavon101
> 
> 👍 This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
> 
> **First let me to point out:**
> 
> * Great commit history! ✔️
> * Professional pull request! ✔️
> 
> Keep on coding, good job so far! 👏
> 
> There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> 
> 
> ## Required Changes ♻️
> * [ ]  Based on retirements, Linter result should be green. Linter should report NO errors. However in your case two tests are failing
>   image
> 
> > please fix the errors and submit project for a new review.
> 
> _Check the comments under the review._
> 
> ## Optional suggestions
> * [ ]   [OPTIONAL] I have noticed that you already have half of your project in main branch, which is a wrong approach. I strongly suggest you to keep all the changes for the current milestone in a feature branch and DO NOT MERGE it before approval 😉
> 
> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.
> 
> Cheers and Happy coding! 👏 👏 👏
> 
> Code review by **Shoira**
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Hi,
I'm having an issue with the `Strylelint`, it's not passing the check. I've tried looking for the solution but it seems everything is okay, please help me out if you can.

**Comment by Bavon101** [comment]
> > ## STATUS: CHANGES REQUIRED 🟡
> > Hi @Bavon101
> > 👍 This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
> > **First let me to point out:**
> > 
> > * Great commit history! ✔️
> > * Professional pull request! ✔️
> > 
> > Keep on coding, good job so far! 👏
> > There are some issues that you still need to work on to go to the next project but you are almost there!
> > 
> > ## Required Changes ♻️
> > 
> > * [ ]   Based on retirements, Linter result should be green. Linter should report NO errors. However in your case two tests are failing
> >   image
> > 
> > > please fix the errors and submit project for a new review.
> > 
> > 
> > _Check the comments under the review._
> > ## Optional suggestions
> > 
> > * [ ]    [OPTIONAL] I have noticed that you already have half of your project in main branch, which is a wrong approach. I strongly suggest you to keep all the changes for the current milestone in a feature branch and DO NOT MERGE it before approval 😉
> > 
> > _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.
> > Cheers and Happy coding! 👏 👏 👏
> > Code review by **Shoira**
> > Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> > **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> > _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
> 
> Hi, I'm having an issue with the `Strylelint`, it's not passing the check. I've tried looking for the solution but it seems everything is okay, please help me out if you can.

I've managed to fix it🐱‍🏍

**Review by rustam-tolipov — APPROVED** [review]
## Hi @Bavon101  👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

image

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
